---
title: "Homework 2"
author: "Halenur Kocaman - 2015402036"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Libraries
```{r include=FALSE}
library(readr)
library(dplyr)
library(tidyverse)
library(scatterplot3d)
library(plotly)
library(ggplot2)
library(plot3D)

```

#Reading the Data

```{r}
x<-read.table("C:/Users/asus/Desktop/homework 2/UWave/uWaveGestureLibrary_X_TRAIN.txt")
y<-read.table("C:/Users/asus/Desktop/homework 2/UWave/uWaveGestureLibrary_Y_TRAIN.txt")
z<-read.table("C:/Users/asus/Desktop/homework 2/UWave/uWaveGestureLibrary_Z_TRAIN.txt")

colnames(x)[1]<-"class"
colnames(y)[1]<-"class"
colnames(z)[1]<-"class"
```


#TASK 1

##Class 1

```{r}
ins_1<- as.data.frame(cbind(x=t(filter(x,class==1))[,1],y=t(filter(y,class==1))[,1],z=t(filter(z,class==1))[,1]))[-1,]

ins_1<- data.frame(ins_1,vel_x=cumsum(ins_1$x),vel_y=cumsum(ins_1$y),vel_z=cumsum(ins_1$z))
ins_1<- data.frame(ins_1,pos_x=cumsum(ins_1$vel_x),pos_y=cumsum(ins_1$vel_y),pos_z=cumsum(ins_1$vel_z))
rownames(ins_1) <- 1:nrow(ins_1)
ins_1$row<-as.numeric(rownames(ins_1))/nrow(ins_1)
scatterplot3d(ins_1[,7:9],color=gray(ins_1$row))

```

##Class 2

```{r}
ins_2<- as.data.frame(cbind(x=t(filter(x,class==2))[,2],y=t(filter(y,class==2))[,2],z=t(filter(z,class==2))[,2]))[-1,]

ins_2<- data.frame(ins_2,vel_x=cumsum(ins_2$x),vel_y=cumsum(ins_2$y),vel_z=cumsum(ins_2$z))
ins_2<- data.frame(ins_2,pos_x=cumsum(ins_2$vel_x),pos_y=cumsum(ins_2$vel_y),pos_z=cumsum(ins_2$vel_z))

scatterplot3d(ins_2[,7:9],color="red")

```

##Class 3

```{r}
ins_3<- as.data.frame(cbind(x=t(filter(x,class==3))[,2],y=t(filter(y,class==3))[,2],z=t(filter(z,class==3))[,2]))[-1,]

ins_3<- data.frame(ins_3,vel_x=cumsum(ins_3$x),vel_y=cumsum(ins_3$y),vel_z=cumsum(ins_3$z))
ins_3<- data.frame(ins_3,pos_x=cumsum(ins_3$vel_x),pos_y=cumsum(ins_3$vel_y),pos_z=cumsum(ins_3$vel_z))

scatterplot3d(ins_3[,7:9],color="red")

```

##Class 4

```{r}
ins_4<- as.data.frame(cbind(x=t(filter(x,class==4))[,1],y=t(filter(y,class==4))[,1],z=t(filter(z,class==4))[,1]))[-1,]

ins_4<- data.frame(ins_4,vel_x=cumsum(ins_4$x),vel_y=cumsum(ins_4$y),vel_z=cumsum(ins_4$z))
ins_4<- data.frame(ins_4,pos_x=cumsum(ins_4$vel_x),pos_y=cumsum(ins_4$vel_y),pos_z=cumsum(ins_4$vel_z))

scatterplot3d(ins_4[,7:9],color="red")

```

##Class 5

```{r}
ins_5<- as.data.frame(cbind(x=t(filter(x,class==5))[,1],y=t(filter(y,class==5))[,1],z=t(filter(z,class==5))[,1]))[-1,]

ins_5<- data.frame(ins_5,vel_x=cumsum(ins_5$x),vel_y=cumsum(ins_5$y),vel_z=cumsum(ins_5$z))
ins_5<- data.frame(ins_5,pos_x=cumsum(ins_5$vel_x),pos_y=cumsum(ins_5$vel_y),pos_z=cumsum(ins_5$vel_z))

scatterplot3d(ins_5[,7:9],color="red")

```

##Class 6

```{r}
ins_6<- as.data.frame(cbind(x=t(filter(x,class==6))[,3],y=t(filter(y,class==6))[,3],z=t(filter(z,class==6))[,3]))[-1,]

ins_6<- data.frame(ins_6,vel_x=cumsum(ins_6$x),vel_y=cumsum(ins_6$y),vel_z=cumsum(ins_6$z))
ins_6<- data.frame(ins_6,pos_x=cumsum(ins_6$vel_x),pos_y=cumsum(ins_6$vel_y),pos_z=cumsum(ins_6$vel_z))

scatterplot3d(ins_6[,7:9],color="red")

```

##Class 7

```{r}
ins_7<- as.data.frame(cbind(x=t(filter(x,class==7))[,3],y=t(filter(y,class==4))[,3],z=t(filter(z,class==7))[,3]))[-1,]

ins_7<- data.frame(ins_7,vel_x=cumsum(ins_7$x),vel_y=cumsum(ins_7$y),vel_z=cumsum(ins_7$z))
ins_7<- data.frame(ins_7,pos_x=cumsum(ins_7$vel_x),pos_y=cumsum(ins_7$vel_y),pos_z=cumsum(ins_7$vel_z))

scatterplot3d(ins_7[,7:9],color="red")


```

##Class 8

```{r}
ins_8<- as.data.frame(cbind(x=t(filter(x,class==8))[,1],y=t(filter(y,class==8))[,1],z=t(filter(z,class==8))[,1]))[-1,]

ins_8<- data.frame(ins_8,vel_x=cumsum(ins_8$x),vel_y=cumsum(ins_8$y),vel_z=cumsum(ins_8$z))
ins_8<- data.frame(ins_8,pos_x=cumsum(ins_8$vel_x),pos_y=cumsum(ins_8$vel_y),pos_z=cumsum(ins_8$vel_z))

scatterplot3d(ins_8[,7:9],color="red")

```

#TASK 2

##Data Preparation

```{r}
colnames(x)[2:316]<-c(1:315)
colnames(y)[2:316]<-c(1:315)
colnames(z)[2:316]<-c(1:315)

x<-cbind(observation=c(1:nrow(x)),x)
x_long<-gather(x,key="time index", value= "x",c(3:317))

y<-cbind(observation=c(1:nrow(y)),y)
y_long<-gather(y,key="time index", value= "y",c(3:317))

z<-cbind(observation=c(1:nrow(z)),z)
z_long<-gather(z,key="time index", value= "z",c(3:317))

df<-cbind(x_long,y=y_long$y,z=z_long$z)
```

```{r}
summary(df) #To check if scaling is needed.
df_pca<-princomp(df[,-c(1:3)])
summary(df_pca, loadings=T)
```

 #TASK 3
 
 Class olarak ayýrýnca ilk component ýn varyansý açýklayabilmesi artýyor.
 ##LONG WAY
 
```{r}
df_1<-filter(df,class==1)
df_2<-filter(df,class==2)
df_3<-filter(df,class==3)
df_4<-filter(df,class==4)
df_5<-filter(df,class==5)
df_6<-filter(df,class==6)
df_7<-filter(df,class==7)
df_8<-filter(df,class==8)

df_1_pca<-princomp(df_1[,-c(1:3)])
summary(df_1_pca, loadings=T)

df_2_pca<-princomp(df_2[,-c(1:3)])
summary(df_2_pca, loadings=T)

df_3_pca<-princomp(df_3[,-c(1:3)])
summary(df_3_pca, loadings=T)

df_4_pca<-princomp(df_4[,-c(1:3)])
summary(df_4_pca, loadings=T)

df_5_pca<-princomp(df_5[,-c(1:3)])
summary(df_5_pca, loadings=T)

df_6_pca<-princomp(df_6[,-c(1:3)])
summary(df_6_pca, loadings=T)

df_7_pca<-princomp(df_7[,-c(1:3)])
summary(df_7_pca, loadings=T)

df_8_pca<-princomp(df_8[,-c(1:3)])
summary(df_8_pca, loadings=T)
```
 
 ##SHORT WAY
```{r}
pca_df<-df %>% split(.$class) %>% map(~princomp(.[,-c(1:3)]))
map(pca_df,summary)
```
 
 